name: "ESP32 GRBL SUBD Stepcraft 300"
board: "https://github.com/JochiSt/ESP32_GRBL_SUBD"

stepping:
  engine: RMT
  idle_ms: 200
  dir_delay_us: 6
  pulse_us: 10
  disable_delay_us: 6

axes:
  shared_stepper_disable_pin: gpio.13:high:pd
  
  x:
    steps_per_mm: 80
    max_rate_mm_per_min: 4000
    acceleration_mm_per_sec2: 100
    max_travel_mm: 1000
    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false
      
    motor0:
      limit_all_pin: gpio.25:high:pd
      standard_stepper:
        step_pin: gpio.12
        direction_pin: gpio.14
    motor1:
      null_motor:

  y:
    steps_per_mm: 80
    max_rate_mm_per_min: 4000
    acceleration_mm_per_sec2: 100
    max_travel_mm: 1000
    homing:
      cycle: 3
      mpos_mm: 10
      positive_direction: false

    motor0:
      limit_all_pin: gpio.33:high:pd
      standard_stepper:
        direction_pin: gpio.15
        step_pin: gpio.02
    motor1:
      null_motor:

  z:
    steps_per_mm: 80
    max_rate_mm_per_min: 4000
    acceleration_mm_per_sec2: 100
    max_travel_mm: 1000
    homing:
      cycle: 1
      mpos_mm: 10
      positive_direction: true

    motor0:
      limit_all_pin: gpio.32:high:pd
      standard_stepper:
        direction_pin: gpio.00
        step_pin: gpio.04
    motor1:
      null_motor:

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

coolant:
  flood_pin: gpio.27:high:pd

control:
  safety_door_pin: NO_PIN
  reset_pin: gpio.34
  feed_hold_pin: gpio.36:low:pu
  cycle_start_pin: gpio.39:low:pu
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

probe:
  pin: gpio.35:low

start:
  must_home: true

besc:
  pwm_hz: 50
  output_pin: gpio.21
  enable_pin: gpio.22:high:pd
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 2000
  spindown_ms: 2000
  tool_num: 100
  speed_map: 0=0.000% 255=100.000%
  min_pulse_us: 1000
  max_pulse_us: 2000
